# Use an official OpenJDK runtime as the base image
FROM openjdk:17-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by Gradle to the container
COPY build/libs/challenging-0.0.1-SNAPSHOT.jar .

# Expose the port your Spring Boot app listens on (default is 8080)
EXPOSE 8080

# Define the command to start your Spring Boot application
CMD ["java", "-jar", "challenging-0.0.1-SNAPSHOT.jar"]
